####################################################################################################
# App: registration
# Package: com.bobwares.customer
# File: application-local.yml
# Version: 0.1.1
# Turns: 2
# Author: Bobwares
# Date: 2025-09-11T08:54:27Z
# Exports: spring.datasource.url, spring.datasource.username, spring.datasource.password, spring.jpa.properties.hibernate.default_schema
# Description: Local profile configuration for Postgres via docker-compose.
####################################################################################################

spring:
  datasource:
    url: jdbc:postgresql://localhost:/
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: 

logging:
  level:
    root: INFO
