####################################################################################################
# App: Customer Registration Service
# Package: configuration
# File: application-local.yml
# Version: 0.1.0
# Turns: 2
# Author: AI
# Date: 2025-09-08T05:07:24Z
# Exports: spring.datasource.username, spring.datasource.password
# Description: Local profile overrides using environment variables for DB credentials.
####################################################################################################

spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
