# App: common
# Package: configuration
# File: application.yml
# Version: 0.1.0
# Author: AI
# Date: 2025-09-04T22:11:01Z
# Exports: spring.application.name
# Description: Configures the Spring Boot application name.

spring:
  application:
    name: common
