####################################################################################################
# App: registration
# Package: com.bobwares.customer
# File: application.yml
# Version: 0.1.2
# Turns: 2
# Author: Bobwares
# Date: 2025-09-11T08:54:27Z
# Exports: server.port, spring.jpa.open-in-view, spring.flyway.enabled, management.endpoints.web.exposure.include, tracing.otlp.endpoint
# Description: Base application configuration for all profiles.
####################################################################################################

server:
  port: ${APP_PORT:8080} 

spring:
  application:
    name: registration
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true

tracing:
  otlp:
    endpoint: 
