####################################################################################################
# App: Customer Registration Service
# Package: configuration
# File: application.yml
# Version: 0.1.1
# Turns: 2
# Author: AI
# Date: 2025-09-08T05:07:24Z
# Exports: spring.application.name, spring.datasource.url, spring.jpa.hibernate.ddl-auto, logging.level.root
# Description: Base application configuration with Postgres datasource and logging settings.
####################################################################################################

spring:
  application:
    name: ${COMPOSE_PROJECT_NAME:${project_name:customer-registration-service}}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:app}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

logging:
  level:
    root: INFO